monitor.alsa.rules = [
  {
    matches = [
      {
        node.name = "~alsa_output[.]usb-Topping_DX5_II-00[.].*"
      }
      {
        node.name = "~alsa_output[.]usb-Fractal_Fractal_Scape_Dongle_.*"
      }
    ]
    actions = {
      update-props = {
        session.suspend-timeout-seconds = 0
      }
    }
  }
]
