music_directory "/mnt/Media/Music"
playlist_directory "~/.local/share/mpd/playlists"
db_file "~/.local/share/mpd/database"
state_file "~/.local/share/mpd/state"
auto_update "yes"
bind_to_address "127.0.0.1"
port "6600"

audio_output {
    type "pulse"
    name "PipeWire"
    mixer_type "software"
}
