vo=gpu-next
gpu-api=vulkan
hwdec=vaapi
profile=high-quality
scale=ewa_lanczossharp
cscale=ewa_lanczossharp
volume=50

keep-open=yes
save-position-on-quit=yes
watch-later-dir=~/.local/state/mpv/watch_later
force-window=immediate
window-scale=0.8
keepaspect-window=no

border=yes
osc=no
osd-bar=no
osd-font-size=30
osd-border-size=2
osd-shadow-offset=1

screenshot-format=png
screenshot-directory=~/Pictures/Screenshots

include=~/.config/theme/mpv.conf

ytdl-format="((bestvideo[vcodec^=vp9]/bestvideo)+(bestaudio[acodec=opus]/bestaudio[acodec=vorbis]/bestaudio[acodec=aac]/bestaudio))/best"
